docs/changes.rst
src/euphorie/client/country.py
src/euphorie/client/survey.py
src/euphorie/client/templates/identification.pt
src/euphorie/client/templates/profile.pt
src/euphorie/client/templates/sessions.pt
src/euphorie/client/templates/shell.pt
src/euphorie/client/templates/start.pt
src/euphorie/client/templates/survey_sessions.pt
src/euphorie/client/update.py
src/euphorie/client/utils.py
src/euphorie/content/survey.py
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po

New feature: On a tool, an editor can add an optional message that will be displayed to users in the client as a pop-up (re-using the message-of-the-day feature)

Tool update notification

---

src/euphorie/client/interfaces.py
src/euphorie/client/risk.py
src/euphorie/client/survey.py
src/euphorie/client/templates/risk_identification.pt
src/euphorie/client/templates/shell.pt
src/euphorie/client/utils.py

Exceptions to the client software / behaviour that are necessary for the way OIRA is used in Italy

Italy special

---

docs/changes.rst
src/euphorie/content/templates/settings.pt

Get rid of colour picker + preview, trash the accordion.
This should help to fix recurring problems from TNO in resetting the password

Simplify the sector edit form

---

docs/changes.rst
src/euphorie/client/report.py

Fix undefined variable

---

src/euphorie/client/report.py
src/euphorie/client/survey.py
src/euphorie/client/tests/test_report.py

Major rework of how the lines for the Action Plan XLS are computed. We are re-using the logic from Status, so that risks in optional modules that are deactivated can be filtered out.
Also, some "hand-written" SQL queries are replaced by sqlalchemy ones.

Rework computation of "Status" and "Timeline"

---

docs/changes.rst
src/euphorie/client/navigation.py
src/euphorie/client/survey.py
src/euphorie/client/tests/test_navigation.py
src/euphorie/client/tests/test_report.py

On optional modules: until the user has explicitly answered the module
question as "Yes", consider this module skipped

Optional modules: default is "skip"

---

src/euphorie/client/tests/test_session.py

Remove unused variable

---

src/euphorie/client/browser/webhelpers.py
src/euphorie/client/profile.py
src/euphorie/client/session.py
src/euphorie/client/tests/test_profile.py
src/euphorie/client/tests/test_session.py
src/euphorie/testing.py

This will allow the security to be customized in other projects

Move the security logic to the webhelpers view

---

src/euphorie/client/browser/country.py
src/euphorie/client/model.py
src/euphorie/deployment/commands/upgradedb.py

This allows the group table to be extended in custom projects

Plone5 customizable group

---

src/euphorie/client/browser/session.py
src/euphorie/client/browser/templates/start.pt

Reason: make it easier to use different logic for fetching the image in customer package

Fetch image to be displayed on Start page in code (not in template)

---

src/euphorie/client/browser/templates/start.pt
src/euphorie/client/configure.zcml
src/euphorie/client/widgets/__init__.py
src/euphorie/client/widgets/configure.zcml
src/euphorie/client/widgets/date.py
src/euphorie/client/widgets/templates/checkbox_input.pt
src/euphorie/client/widgets/templates/date_input.pt
src/euphorie/client/widgets/templates/text_input.pt

The start form will include the widgets calling their renderer.
Some widgets are included to have a nice result

Custom widgets for the start form

---

setup.py
src/euphorie/client/utils.py

Remove the unused jsonify decorator that had a dependency on the
simplejson module that we do not want anymore

Remove unused code

---

src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/new-session-test.pt
src/euphorie/client/browser/templates/new-session.pt

Remove sneakily defined class attribute

---

src/euphorie/client/browser/session.py
src/euphorie/client/company.py
src/euphorie/client/pdf.py
src/euphorie/client/report.py
src/euphorie/client/tests/test_report.py

Make sure that no views in a session can be viewed by a user without permission

Security fix

---

src/euphorie/client/browser/webhelpers.py
src/euphorie/client/model.py
src/euphorie/client/tests/test_webhelpers.py

Added the possibility to include in the session query the sessions from my group and its subgroups

New option include_group for the webhelpers.get_sessions_query method

---

src/euphorie/client/browser/risk.py
src/euphorie/client/tests/test_risk.py
src/euphorie/content/profiles/default/registry/imagecropping.xml
src/euphorie/deployment/upgrade/configure.zcml
src/euphorie/deployment/upgrade/profiles.zcml
src/euphorie/deployment/upgrade/profiles/to_0024/registry.xml

Use Training scale

---

src/euphorie/client/model.py

This gives a massive improvement because `g.parent` was making another SQL query to the DB (and we actually do not need that).

Optimize the _group_structure property

---

src/euphorie/client/browser/session.py
src/euphorie/client/browser/templates/publication_menu.pt
src/euphorie/client/tests/test_survey_integration.py
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po

1) Don't record publication as a modification event
2) Show _who_ published a session

Publication change

---

src/euphorie/client/model.py

With the provided patch customer code can customize in an easier way
which tools can be selected as filters

feature: Improve the customizability of the context filter

---

src/euphorie/client/browser/session.py

When copying a session, iterate over all fields in the table, but check if they are actually present

Fix problems when a session is copied / cloned

---

src/euphorie/client/widgets/templates/date_input.pt
src/euphorie/client/widgets/templates/text_input.pt

Fix the widget value by defining a previously undefined name variabled
that was used to lookup the value in the request

Fix the widget value

---

src/euphorie/client/browser/risk.py

Move the computation of the template to be used into a separate method, so that it can be customised.

feat: risk template customizable

---

src/euphorie/client/browser/training.py

view (and not in the template), so that we can calculate the slide total count

Already fetch the training_slide view and the slides inside the Training

---

src/euphorie/client/browser/session.py

so that it can be easily extended in sub-classes

move the setting of the session data into its own method

---

docs/changes.rst
src/euphorie/client/templates/shell.pt

Activated session refresh mechanism from plone.session. Prevents active users from being logged out.
The JS console shows messages from refreshsupport.js detailing if and when the session is being refreshed.

Session Refresh

---

src/euphorie/client/browser/templates/risk_identification.pt
src/euphorie/client/browser/templates/webhelpers.pt

This fixes an ugly reloading of the whole page
I add "hold merge" since right now I don't remember if there was a good reason for the deviation. Firsts tests with training module as well as integrated action plan (mutex at the moment) seem fine. Further tests needed, though.

Make the sub-form behaviour + injection like we have in proto.

---

src/euphorie/client/browser/session.py

In sqlalchemy 1.3, join() is more strict, see
https://docs.sqlalchemy.org/en/14/changelog/migration_13.html#key-behavioral-changes-orm
Therefore, define which table to select from (and simplify joining of Risk table by using
the parent-relationship)

Fix SQL query with multiple joins

---

src/euphorie/client/company.py
src/euphorie/client/model.py
src/euphorie/client/tests/test_company.py
src/euphorie/deployment/upgrade/alembic/versions/20210409113814_.py
src/euphorie/upgrade/deployment/v1/20210409113814_add_timestamp_to_company_questionnaire/upgrade.py

Added timestamp field to company

---

src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/templates/oira_tool.pt

Still needs to be designed
Refs #SCR-958

Create a (dummy) public page for tools

---

src/euphorie/content/configure.zcml
src/euphorie/content/profiles/default/catalog.xml
src/euphorie/content/survey.py
src/euphorie/upgrade/deployment/v1/20210720143221_add_language_index/catalog.xml
src/euphorie/upgrade/deployment/v1/20210720143221_add_language_index/upgrade.py

Needed for the “Tools” filter.
@reinhardt Since you already started working on the filter, you're probably in a good position to review this.

Add language index

---

setup.py
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/templates/browser-warning.pt
src/euphorie/client/browser/templates/shell.pt
src/euphorie/client/browser/webhelpers.py
versions.cfg

Also, prevent loading of our main JavaScript bundle - with an outdated browser, we simply do not offer any service at all any more.
Refs #SCR-1524
Implements https://github.com/syslabcom/oira.prototype/issues/302

Sniff the user agent and issue a warning if we detect IE

---

docs/changes.rst
src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/client/browser/webhelpers.py
src/euphorie/content/browser/solution.py

Clean texts that appear in a structure or pat-markdown context using the safe_html transform

Prevent XSS in text entered by the user (description, measure text).

---

docs/changes.rst
src/euphorie/client/browser/login.py
src/euphorie/client/browser/webhelpers.py
src/euphorie/deployment/profiles/default/registry.xml
src/euphorie/upgrade/deployment/v1/20211216172426_toggle_for_self_registration/registry.xml
src/euphorie/upgrade/deployment/v1/20211216172426_toggle_for_self_registration/upgrade.py

Make self-registration the default - but disable the possibility to register if that setting is turned off.

Respect security setting for self-registration

---

docs/changes.rst
src/euphorie/client/browser/webhelpers.py

of the language name from the zope locales

Fix getNameForLanguageCode: we actually need to look up the translation

---

docs/changes.rst
src/euphorie/content/browser/upload.py

Fix data import

---

src/euphorie/client/browser/risk.py

The default answers (yes, no, n/a) might be tool-type specific

Don't assume all default answers come from default

---

docs/changes.rst
src/euphorie/client/browser/login.py
src/euphorie/client/browser/templates/login.pt
src/euphorie/client/browser/templates/register_session.pt

It is redundant and we have better ways to know it

Do not use the guest_account_id in the login and register forms

---

docs/changes.rst
src/euphorie/client/browser/templates/risk_identification.pt
src/euphorie/client/browser/templates/webhelpers.pt

Fix injection-related problem on tools with integrated action plan that also use measures in place

Fix injection problem

---

docs/changes.rst
src/euphorie/client/browser/risk.py

Fix bug that prevented deleting Omega risks

---

docs/changes.rst
src/euphorie/client/browser/session.py
src/euphorie/client/browser/templates/panel-contents-preview.pt
src/euphorie/client/docx/compiler.py

Show descriptions in print preview and measures in Word preview.
Refs syslabcom/scrum#146

Consolidate previews

---

docs/changes.rst
src/euphorie/client/docx/compiler.py

Identification report: Show ZODB measures (solutions), not action plan.
Refs syslabcom/scrum#194

Consolidate previews 2

---

src/euphorie/client/browser/training.py
src/euphorie/client/tests/test_training_questions.py
src/euphorie/content/survey.py

Training questions: Pick a random subset of questions per training session.
Refs syslabcom/scrum#195

Training questions: Randomize

---

src/euphorie/client/browser/templates/surveys.pt

Refs https://github.com/syslabcom/scrum/issues/240

Comment out the sector pills

---

src/euphorie/client/browser/webhelpers.py
src/euphorie/client/tests/test_training_questions.py
src/euphorie/content/browser/survey.py
src/euphorie/content/country.py
src/euphorie/content/tests/test_country.py

The three levels of switches (global, country, tool) are potentially confusing and at least the wording should be improved, but we don't have time for that right now.
Refs syslabcom/scrum#295

Training toggle on country level

---

docs/changes.rst
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/login.py
src/euphorie/client/browser/settings.py
src/euphorie/client/browser/templates/login.pt
src/euphorie/client/browser/templates/preferences.pt
src/euphorie/client/model.py
src/euphorie/client/tests/test_functional_login.py
src/euphorie/deployment/upgrade/alembic/versions/20220620103222_.py
src/euphorie/upgrade/client/v1/20220620103222_add_first_and_last_name_to_user/upgrade.py

User account: first name and last name

---

docs/changes.rst
src/euphorie/client/browser/templates/actionplan.pt
src/euphorie/client/browser/templates/identification.pt
src/euphorie/client/browser/templates/involve.pt
src/euphorie/client/browser/templates/module_actionplan.pt
src/euphorie/client/browser/templates/module_identification.pt
src/euphorie/client/browser/templates/module_identification_custom.pt
src/euphorie/client/browser/templates/profile.pt
src/euphorie/client/browser/templates/report.pt
src/euphorie/client/browser/templates/report_company.pt
src/euphorie/client/browser/templates/report_landing.pt
src/euphorie/client/browser/templates/risk_identification_custom.pt
src/euphorie/client/browser/templates/start.pt
src/euphorie/client/browser/templates/status_info.pt
src/euphorie/client/browser/templates/updated.pt

See https://github.com/syslabcom/oira.prototype/commit/1d5be4e0e8be89629c507464b779b3d937d3aadf
Refs syslabcom/scrum#404

Added pat-scroll-box

---

src/euphorie/client/browser/templates/training-slides.pt
src/euphorie/client/browser/templates/training.pt
src/euphorie/client/browser/training.py

Will be used in daimler. They don't want the byline.
Refs syslabcom/scrum#419

Training: Allow hiding slide byline

---

docs/changes.rst
src/euphorie/client/browser/templates/tool_sessions.pt

Tool view: "show more" button if there are existing sesions.
Refs syslabcom/scrum#445

"Show more" button on tool view

---

src/euphorie/client/browser/login.py
src/euphorie/client/utils.py
src/euphorie/deployment/commands/xmlimport.py
src/euphorie/deployment/setuphandlers.py
src/euphorie/testing.py
src/euphorie/upgrade/deployment/v1/20220706144723_activate_secure_session_cookie/upgrade.py

Fix SCAS findings

---

docs/changes.rst
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/robots.py
src/euphorie/client/browser/templates/robots.txt

Refs https://github.com/syslabcom/scrum/issues/378

Add a robots.txt view to the client

---

src/euphorie/client/browser/organisation.py
src/euphorie/client/browser/templates/organisation.pt
src/euphorie/client/model.py

Use the user name when possible in the organisation views

---

docs/changes.rst
src/euphorie/client/adapters/configure.zcml
src/euphorie/client/adapters/json.py
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/session.py
src/euphorie/client/tests/test_export.py

Added an `@@export.json` view that allows to export a session and the
related content in a single json file

Added a way to serialize a session

---

src/euphorie/client/browser/templates/login.pt
src/euphorie/deployment/profiles/default/registry.xml
src/euphorie/upgrade/deployment/v1/20220805134335_make__keep_me_logged_in__checkbox_optional/registry.xml
src/euphorie/upgrade/deployment/v1/20220805134335_make__keep_me_logged_in__checkbox_optional/upgrade.py

"Remember login" feature switch

---

docs/changes.rst
src/euphorie/content/browser/configure.zcml
src/euphorie/content/browser/country.py
src/euphorie/content/browser/templates/country_tools.pt
src/euphorie/content/sector.py
src/euphorie/content/tests/test_functional_sector.py

Tool overview on country level

---

src/euphorie/content/browser/export.py
src/euphorie/content/browser/upload.py
src/euphorie/content/tests/test_export.py
src/euphorie/content/tests/test_functional_upload.py

Include Training Questions in the export/import
Refs https://github.com/syslabcom/scrum/issues/353

Export/import Training Questions

---

docs/changes.rst
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/assessments.pt

Assessments filters

---

src/euphorie/client/browser/templates/sessions-dashboard.pt

Make sure the #toolbar-functions-area is present because the nav injection needs it.
Best viewed [ignoring whitespace](https://github.com/euphorie/Euphorie/pull/450/files?diff=split&w=1)
Refs syslabcom/scrum#597

Fix navigation injection

---

src/euphorie/client/browser/templates/sessions-dashboard.pt
src/euphorie/client/browser/webhelpers.py

The organisation tab can be hidden by setting the `@@webhepers` property `hide_organisation_tab` to `True`

Added a way to hide the organisation tab

---

src/euphorie/client/browser/organisation.py
src/euphorie/client/browser/templates/panel-add-user-to-organisation.pt

Commented for the moment because it is still under discussion

Comment the Manager/Policy maker role

---

src/euphorie/client/browser/templates/sessions-dashboard.pt

Tweaked #toolbar-functions-area.
* more conformant with proto
* no `form` tag without a function
See also https://github.com/euphorie/Euphorie/pull/450
Refs https://github.com/syslabcom/scrum/issues/597

Fix navigation injection (revisited)

---

src/euphorie/client/browser/templates/webhelpers.pt

Refs syslabcom/scrum#596
See also #473 for styles and #437 for regular (not in-place) measures

Use rich text (tiptap) for measures in place

---

src/euphorie/client/widgets/templates/date_input.pt

Related:‌
- https://gitlab.com/syslabcom/daimler/daimler.oira/-/merge_requests/170
- https://github.com/euphorie/Euphorie/pull/474
Ref: https://github.com/syslabcom/scrum/issues/705

Date widget: Add required attribute depending on field state.

---

docs/changes.rst
src/euphorie/client/browser/templates/risk_identification_custom.pt
src/euphorie/client/browser/templates/webhelpers.pt

Fix the tiptap configuration.
Ref: #scrum-707

Fix issue where tiptap link context menu didn't load.

---

docs/changes.rst
src/euphorie/client/browser/templates/sessions-dashboard.pt

Refs https://github.com/syslabcom/scrum/issues/747

Prepare the dashboard to have banners

---

docs/changes.rst
src/euphorie/client/docx/compiler.py
src/euphorie/client/docx/views.py

docx report: measures rich text

---

docs/changes.rst
src/euphorie/content/browser/configure.zcml
src/euphorie/content/browser/country.py
src/euphorie/content/browser/templates/country_tools.pt

CSV download of country tools

---

docs/changes.rst
setup.py
src/euphorie/deployment/browser/sitemenu.py
src/euphorie/deployment/tests/test_sitemenu.py

Together:
https://github.com/euphorie/NuPlone/pull/42
https://github.com/euphorie/Euphorie/pull/490
https://github.com/euphorie/osha.oira/pull/180
Fixes: https://github.com/syslabcom/scrum/issues/837

Add the @@country-tools view to the site menu.

---

src/euphorie/client/docx/html.py

This is an attempt to simplify the code base and to benefit from developments from other package and vice versa.
In the end this should solve issues with broken formats, especially with risk measurement lists.
Ref: scrum-951

Align the euphorie.client.docx.html module with customized overrides from other projects.

---

docs/changes.rst
src/euphorie/content/browser/templates/country_tools.pt

Info paragraph for country tools

---

docs/changes.rst
src/euphorie/client/browser/templates/training-slides.pt
src/euphorie/client/browser/templates/training.pt
src/euphorie/client/browser/training.py

Add headings for existing and planned measures, respectively.
syslabcom/scrum#997

Add measure headings

---

docs/changes.rst
src/euphorie/client/browser/templates/webhelpers.pt

Refs: https://github.com/syslabcom/scrum/issues/901

Fix the layout of the Budget field for Measures

---

docs/changes.rst
src/euphorie/client/browser/templates/tool_sessions.pt

Very similar to: https://github.com/euphorie/Euphorie/pull/481
Custom policy packages might use this feature or not.

Tool view banner

---

docs/changes.rst
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/assessments.pt

Refs: https://github.com/syslabcom/scrum/issues/1040

@@assessments: Change the default sort order to newest first

---

docs/changes.rst
requirements.txt
versions.cfg

Merge together:
- https://github.com/EU-OSHA/oira.application.buildout/pull/18
- https://github.com/euphorie/Euphorie/pull/513

Upgrade Plone to 5.2.11.

---

docs/changes.rst
src/euphorie/client/navigation.py

Refs: https://github.com/syslabcom/scrum/issues/1041

Sidebar: render siblings of the selected profile question module

---

docs/changes.rst
src/euphorie/client/browser/configure.zcml

Refs. https://github.com/syslabcom/scrum/issues/1043

Restrict the assessments view to authenticated users

---

src/euphorie/client/navigation.py

Refs: https://github.com/syslabcom/scrum/issues/1041

getTreeData: Don't change the order of the siblings

---

src/euphorie/client/browser/organisation.py
src/euphorie/client/browser/templates/notify-invite-accept.pt

Confirm organisation invite mail

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Also fix an error in Italian
syslabcom/scrum#594

Add new extracted translation strings [ci skip]

---

docs/changes.rst
src/euphorie/client/browser/organisation.py

Deployment postponed because translations are missing.
syslabcom/scrum#1133

Deactivate organisation invite confirmation

---

src/euphorie/client/browser/consultancy.py
src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/client/browser/templates/notify-request-validation.pt
src/euphorie/client/model.py
src/euphorie/client/tests/test_consultancy.py
src/euphorie/deployment/upgrade/alembic/versions/20230421141443_add_consultancy_table.py
src/euphorie/upgrade/deployment/v1/20230421141443_add_consultancy_table/upgrade.py

Includes #533; merge that one first

Request validation from consultant

---

src/euphorie/client/browser/consultancy.py
src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/client/browser/templates/notify-request-validation.pt

If you want to review step-by-step check these PRs in order: #533, #536, #537
Or merge this and close the above.

Validation refactor and polish

---

docs/changes.rst
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/assessments.pt
src/euphorie/client/browser/templates/user-menu.pt

See https://github.com/euphorie/Euphorie/blob/2cdd6a50d2e6966ef631c1ec0115323f149760dc/src/euphorie/deployment/locales/euphorie.pot#L25
Also includes #542

Fix unused i18n statement

---

docs/changes.rst
src/euphorie/client/browser/organisation.py

Undo #539 and #540
syslabcom/scrum#1133

Reactivate organisation invite confirmation mail

---

src/euphorie/client/browser/templates/panel-add-user-to-organisation.pt
src/euphorie/client/browser/templates/panel-organisation-member-edit.pt
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

https://github.com/syslabcom/scrum/issues/1136

Labels for organisation members add/edit

---

src/euphorie/client/browser/consultancy.py
src/euphorie/client/tests/test_consultancy.py

Only the consultant assigned to a risk assessment can validate it
<del>Contains #546, consider rebasing after merging #546 </del> rebased
syslabcom/scrum#1105

Validation: Consultant Permission

---

src/euphorie/client/browser/consultancy.py
src/euphorie/client/browser/templates/consultancy.pt

When the consultant views the validated assessment, show a message saying that she has validated it.
syslabcom/scrum#1105

Fix consultancy template

---

docs/changes.rst
src/euphorie/client/browser/templates/risk_identification.pt
src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/client/browser/webhelpers.py

When there is no measure to select, do not show the "Training" module.
contains #556

Optional training module

---

docs/changes.rst
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/new-session.pt

https://github.com/syslabcom/scrum/issues/1137

Duplication via new-session.html

---

src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/new-session-test.pt
src/euphorie/client/browser/templates/portlet-available-tools.pt

I also checked tno and daimler and it's not used there either.
See also #559 
https://github.com/syslabcom/scrum/issues/1137

clean up unused tools_threshold

---

docs/changes.rst
src/euphorie/client/browser/templates/portlet-available-tools.pt

Align with recent changes in prototype.

---

src/euphorie/client/browser/consultancy.py
src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/client/model.py
src/euphorie/client/tests/test_consultancy.py
src/euphorie/deployment/upgrade/alembic/versions/20230504061955_add_sessionevent_table.py
src/euphorie/deployment/upgrade/alembic/versions/20230515143459_allow_consultant_deletion.py
src/euphorie/upgrade/deployment/v1/20230504061955_add_session_event_table/upgrade.py
src/euphorie/upgrade/deployment/v1/20230515143459_allow_consultant_deletion/upgrade.py

To do: Backport the session history from daimler.oira and integrate SessionValidated and SessionValidationRequested.
syslabcom/scrum#1162

Validation: Record session events

---

docs/changes.rst
src/euphorie/client/browser/organisation.py
src/euphorie/client/browser/templates/panel-add-user-to-organisation.pt

Don't show consultant role if consultancy phase is disabled

---

docs/changes.rst
src/euphorie/client/browser/templates/portlet-my-trainings.pt
src/euphorie/client/browser/training.py

Training portlet: avoid redirect after tool has been updated

---

src/euphorie/client/browser/templates/consultancy.pt

Consultancy: display date as prefix

---

src/euphorie/client/browser/webhelpers.py

Keep consultancy phase enabled when assessment is locked

---

src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Tweak text: find consultants

---

setup.py

It is a relic from the past AT era

Do not depend anymore on plone.app.folder

---

src/euphorie/client/browser/consultancy.py

Consultancy: Don't break if a user doesn't have an organisation

---

src/euphorie/client/browser/templates/consultancy.pt

Consultancy: Scroll to relevant help paragraph

---

src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/consultancy.py
src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/client/browser/templates/consultants.pt
src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/client/browser/webhelpers.py

Populate link “Find an OSH consultant”

---

docs/changes.rst
src/euphorie/client/browser/webhelpers.py
src/euphorie/content/country.py
src/euphorie/deployment/profiles/default/registry.xml
src/euphorie/upgrade/deployment/v1/20230606094424_remove_use_consultancy_phase_feature_switch/registry.xml
src/euphorie/upgrade/deployment/v1/20230606094424_remove_use_consultancy_phase_feature_switch/upgrade.py

Consultancy feature flag per country

---

docs/changes.rst
src/euphorie/client/docx/compiler.py
src/euphorie/client/docx/views.py

except for France and Italy when measures in place are active
syslabcom/scrum#1245

Show solution descriptions in the Word report

---

src/euphorie/client/browser/organisation.py
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

https://github.com/syslabcom/scrum/issues/1267

Consultancy translations tweak

---

src/euphorie/client/tests/test_risk.py
src/euphorie/deployment/products.py
src/euphorie/deployment/tests/test_setup.py

Small updates to fix some tests in Plone 6

Plone 6 preparation

---

src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Add missing i18n name

---

docs/changes.rst
src/euphorie/client/browser/templates/report.pt
src/euphorie/client/browser/templates/report_company.pt

Align with prototype to fix form style issues.

---

src/euphorie/client/browser/templates/consultants.pt
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Text tweak “find a consultant”

---

src/euphorie/client/browser/templates/locking_menu.pt

fix validation time in locking menu

---

src/euphorie/client/browser/templates/consultants.pt

follow-up of #602
syslabcom/scrum#1285

Text tweak “find a consultant”, part 2

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Extract translation msgids

---

src/euphorie/client/browser/country.py

assessments.json: Use placeholder for missing title

---

src/euphorie/client/adapters/configure.zcml
src/euphorie/client/adapters/history_item.py
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/history.py
src/euphorie/client/browser/templates/history_popup.pt
src/euphorie/client/browser/templates/more_menu.pt
src/euphorie/client/tests/test_history_popup.py

Add the history popup

---

src/euphorie/client/browser/consultancy.py

This is consistent to what is done in the lock menu: https://github.com/euphorie/Euphorie/blob/0e6635b7d33eba30e05558a715bf25da9929cb5d/src/euphorie/client/config.py#L5
https://github.com/euphorie/Euphorie/blob/0e6635b7d33eba30e05558a715bf25da9929cb5d/src/euphorie/client/browser/locking.py#L72

Change the name of the action

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

I ran just `make pot` in the root of the package Euphorie, I think I never did that.
I am not sure why we have so many strange changes, e.g.:
```diff
-"Language: deployment\n"
+"Language: bg\n"
```
```diff
-#: Euphorie/src/euphorie/client/browser/templates/login.pt:327
+#: euphorie/client/browser/templates/login.pt:327
```
Maybe I am not doing that properly?

Run make pot

---

src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po

https://github.com/syslabcom/scrum/issues/1267

corrected some text and variables

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po

Fix translations

---

docs/changes.rst
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po

German translations related to cloning

---

src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po

corrected wrong translation for #1620

---

src/euphorie/client/docx/compiler.py

Factored out unnecessary loop.

---

src/euphorie/client/docx/compiler.py

Fix error in Italy report caused by short report changes

---

docs/changes.rst
src/euphorie/content/browser/configure.zcml
src/euphorie/content/browser/survey.py
src/euphorie/content/browser/templates/find-tools-with-duplications.pt

Add view find-tools-with-duplications

---

docs/changes.rst
src/euphorie/client/browser/login.py

This changes are necessary after
https://github.com/plone/plone.session/pull/44

Fix login to be Plone 6 compatible

---

docs/changes.rst
src/euphorie/content/browser/module.py
src/euphorie/content/browser/profilequestion.py
src/euphorie/content/browser/survey.py

This cleans up some browser views which replicated the same code over multiple classes.
This PR‌ unifies the situation for the cost of an additional class to be inherited.

Cleanup: Reuse similar code for survey related views.

---

src/euphorie/client/notifications/notification__ra_not_modified.py
src/euphorie/client/tests/test_notifications.py

Fix get_responsible_users (incl. some basic notifications tests)

---

src/euphorie/client/notifications/base.py

Notifications: Correct the preferences link in notification mails.

---

docs/changes.rst
src/euphorie/client/browser/settings.py
src/euphorie/client/notifications/base.py
src/euphorie/client/notifications/notification__ra_not_modified.py
src/euphorie/client/notifications/send_notifications.py
src/euphorie/client/tests/test_notifications.py
src/euphorie/deployment/profiles/default/registry.xml
src/euphorie/upgrade/deployment/v1/20231128125729_notifications_registry_entries/registry.xml
src/euphorie/upgrade/deployment/v1/20231128125729_notifications_registry_entries/upgrade.py

Implementing: https://github.com/syslabcom/scrum/issues/1572#issuecomment-1825472210
Merge all:
https://github.com/euphorie/Euphorie/pull/673
https://github.com/syslabcom/daimler.oira/pull/257
https://github.com/syslabcom/daimlertruck.policy/pull/1
https://github.com/syslabcom/mercedesbenz.policy/pull/2

Notifications: Implementing review comments

---

docs/implementation/client/index.rst
docs/implementation/client/registry.rst

Notifications: Add some basic docs for the registry keys.

---

src/euphorie/client/tests/test_notifications.py

Notifications: Enable notifications when testing them.

---

src/euphorie/client/notifications/base.py

Fixes error when tool cannot be retrieved, like in tests
syslabcom/scrum#1572

Notifications: Get country directly from session

---

docs/changes.rst
src/euphorie/client/browser/company.py

See, e.g. https://github.com/euphorie/tno.euphorie/pull/17

Allow the company model to be customized by other packages

---

docs/changes.rst
src/euphorie/client/model.py

See also https://github.com/euphorie/Euphorie/issues/609
syslabcom/scrum#1888

Add alias in RISK_PRESENT_FILTER_TOP5_TNO_FILTER

---

docs/changes.rst
setup.py
src/euphorie/client/client.py

Skin layer entry point

---

src/euphorie/client/browser/templates/plain.pt

Weasyprint: Increase font size

---

src/euphorie/client/browser/templates/plain.pt

Weasyprint: Decrease h3 font size

---

src/euphorie/client/docx/compiler.py

Short report: No icon for skipped risks

---

src/euphorie/client/browser/risk.py
src/euphorie/client/browser/templates/risk_actionplan.pt
src/euphorie/client/configure.zcml
src/euphorie/client/model.py
src/euphorie/client/navigation.py
src/euphorie/content/utils.py

Then we can override the browser view for psychosocial sessions.

Refactor getTreeData to use browser view

---

docs/changes.rst
src/euphorie/client/browser/templates/report_landing.pt
src/euphorie/client/docx/compiler.py
src/euphorie/content/country.py

Make short report configurable

---

docs/changes.rst
src/euphorie/client/browser/templates/status_info.pt

Fix locking info in status view

---

src/euphorie/client/docx/compiler.py

Fix description_of_measures

---

src/euphorie/client/docx/views.py
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Custom file name for short report

---

src/euphorie/client/browser/risk.py
src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/client/browser/webhelpers.py

We will use this to more easily override these parts.

webhelpers: add navigation_tree_legend and use_action_plan_phase methods 

---

docs/changes.rst
src/euphorie/content/browser/configure.zcml

Change permission on duplication finder views to ManageCountry

---

docs/changes.rst
src/euphorie/client/browser/publish.py

Fix regression introduced in https://github.com/euphorie/Euphorie/pull/692

Do not do linkintegrity checks when removing contents

---

src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/client/browser/webhelpers.py

Cherry picked from @mauritsvanrees PR
https://github.com/euphorie/Euphorie/pull/715

Allow the legend to be customized

---

src/euphorie/content/browser/similar_titles_details.py

Similar Titles: Use semicolon as delimiter

---

docs/changes.rst
src/euphorie/client/browser/certificates.py
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/templates/certificates.pt
src/euphorie/client/browser/templates/sessions-dashboard.pt
src/euphorie/client/browser/templates/training_certificate_view.pt
src/euphorie/client/browser/webhelpers.py

Add certificates overview

---

docs/changes.rst
src/euphorie/client/browser/certificate.py
src/euphorie/client/browser/certificates.py
src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/templates/status_info.pt

Note: There will be another PR to consolidate the `certificate` and `certificates` modules (needs to be coordinated with osha.oira)
Contains #733 
Ref https://github.com/syslabcom/scrum/issues/2143

Show certificates on assessment status page

---

src/euphorie/client/browser/templates/training_certificate_view.pt

Certificate view: Don't require a training_id to be passed

---

src/euphorie/client/browser/certificate.py

Certificates overview: Show own certificates if the user has no organisation

---

src/euphorie/deployment/browser/configure.zcml
src/euphorie/deployment/browser/maintenance.py

Convert upgrade step to maintenance view

---

docs/changes.rst
src/euphorie/deployment/browser/maintenance.py

Refs. https://github.com/syslabcom/scrum/issues/2372

Fix the last modifier id for guest users that have been converted to registered users

---

docs/changes.rst
src/euphorie/client/browser/certificate.py
src/euphorie/client/browser/templates/certificates.pt

Certificates overview: set CSS class according to number of items

---

docs/changes.rst
src/euphorie/client/model.py

copySessionData: Include scaled_answer

---

docs/changes.rst
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po

Fix nl-BE translation

---

docs/changes.rst
src/euphorie/client/browser/report.py

ActionPlanTimeline: convert risk comment to plain text

---

src/euphorie/client/browser/report.py

Follow-up for #767 
Ref syslabcom/scrum#2763

ActionPlanTimeline: Strip whitespace when converting to plain text

---

setup.cfg

(to save pypi space)
Ref syslabcom/scrum#2772

Don't create wheels

---

src/euphorie/client/tests/test_report.py

Thanks to your comment in #770 I found some tests for the queries, which inspired a test for the query for unanswered risks (https://github.com/euphorie/osha.oira/pull/290). I then ported that to Euphorie.
I did verify that it fails without the fix in #770.
This of course still needs some cleanup - maybe porting all related tests to Euphorie and removing the respective code from osha.oira (if it indeed turns out to be unused).
Ref syslabcom/scrum#2800

Test for unanswered risks query

---

docs/changes.rst
src/euphorie/client/model.py
src/euphorie/client/tests/test_report.py

Analogous to #770 
Ref syslabcom/scrum#2800

Fix query for risks that are not present

---

src/euphorie/client/model.py

See also #770 and #773
This version hopefully performs better for large sessions.
Ref syslabcom/scrum#2800

Alternative fix for unanswered / not present risks

---

docs/changes.rst
src/euphorie/client/docx/compiler.py
src/euphorie/client/docx/views.py
src/euphorie/content/country.py

Ref https://github.com/syslabcom/scrum/issues/2815

Add legal and policy references as an option for the compact report

---

docs/changes.rst
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po

Ref https://github.com/syslabcom/scrum/issues/3015

German translations related to locking

---

docs/changes.rst
src/euphorie/client/browser/templates/report_company.pt

We're not going through the translation mechanism here because other French speaking countries (Belgium) should not be affected.
Ref https://github.com/syslabcom/scrum/issues/2375

Custom labels in report_company for France

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Ref https://github.com/syslabcom/scrum/issues/3105

Add new translation msgids (extracted with i18ndude)

---

docs/changes.rst
src/euphorie/client/docx/compiler.py
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Ref https://github.com/syslabcom/scrum/issues/3105

Short report: translate table headers

---

docs/changes.rst
src/euphorie/client/docx/compiler.py

Ref https://github.com/syslabcom/scrum/issues/3090

Short report: Only show Measures in Place heading if tool supports it

---

src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po

added missing translations for comments section headline in report

---

docs/changes.rst
src/euphorie/client/browser/webhelpers.py

Check edit permission in redirectOnSurveyUpdate

---

src/euphorie/client/browser/templates/history_popup.pt
src/euphorie/client/browser/templates/login.pt
src/euphorie/client/browser/templates/sharing_badge.pt
src/euphorie/client/browser/templates/status_info.pt
src/euphorie/client/browser/templates/webhelpers.pt

Refs https://github.com/syslabcom/scrum/issues/3181 and fixes Angels blockers for a release.

3181 markup fixes

---

src/euphorie/client/browser/templates/report_company.pt

Fixes erroneous line breaks
Ref syslabcom/scrum#3181

report_company: remove span tag

---

news/3288.bugfix
src/euphorie/client/docx/views.py

Report: Handle risk `None` (custom risk)

---

news/+f95a6765.feature.rst
src/euphorie/content/browser/risk.py

While this is not directly used in Euphorie code, it is convenient for customers code.

Add a tool_type_data property in the risk view class

---

news/+37b1efc1.internal.rst
src/euphorie/content/survey.py

The function was importing code defined in the same module were it lived

Remove unused import

---

.github/workflows/main.yml

see https://gh.io/gha-cache-sunset

Old cache api was sundowned today by github

---

.github/workflows/main.yml
news/3385.feature.rst
src/euphorie/client/browser/organisation.py

This has been urgently requested by Frank and Lia. 
We tested in the usability test.
Having it reduces a lot of distractions for the users.

#3385 Create organisation by default

---

src/euphorie/client/browser/templates/portlet-my-ras.pt
src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/euphorie.pot
src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po

Refs #3384
If there are no assessments, a message is displayed.

Added empty portlet message incl translations

---

.github/workflows/main.yml
news/3384.fixes.rst
src/euphorie/client/browser/templates/actionplan.pt
src/euphorie/client/browser/templates/consultancy.pt
src/euphorie/client/browser/templates/help-menu.pt
src/euphorie/client/browser/templates/identification.pt
src/euphorie/client/browser/templates/module_actionplan.pt
src/euphorie/client/browser/templates/module_identification.pt
src/euphorie/client/browser/templates/module_identification_custom.pt
src/euphorie/client/browser/templates/organisation.pt
src/euphorie/client/browser/templates/panel-edit-organisation.pt
src/euphorie/client/browser/templates/portlet-available-tools.pt
src/euphorie/client/browser/templates/portlet-my-ras.pt
src/euphorie/client/browser/templates/report_company.pt
src/euphorie/client/browser/templates/risk_macros.pt
src/euphorie/client/browser/templates/surveys.pt
src/euphorie/client/browser/templates/tool_sessions.pt
src/euphorie/client/browser/templates/webhelpers.pt
src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po
src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po

Contains all pure markup fixes made before and during the usability testing and which were considered helpful.
All markup changes require plonestatic.euphorie dated March 28 or later.

3384 markup fixes

---

news/+952c116d.bugfix.rst
src/euphorie/client/browser/risk.py

The parameters that are set are now lazily evaluated when needed.
This removes some duplicated code.
This will be used in OiRA creator, refs. https://github.com/syslabcom/scrum/issues/3059

Clean up set_parameter_values

---

news/+5f195a77.bugfix.rst
src/euphorie/content/browser/risk.py

This might happen, e.g., if you add a behavior to your content type.

Do not break if we have unexpected fieldsets

---

src/euphorie/client/browser/configure.zcml
src/euphorie/client/browser/matomo.py
src/euphorie/client/browser/webhelpers.py

proof of concept for:
- a matomo custom dimensions endpoint
- a matomo tracking mock backend
https://github.com/euphorie/Euphorie/pull/838
https://github.com/euphorie/osha.oira/pull/324

Matomo custom dimensions endpoint

---

news/+30375d2c.bugfix.rst
src/euphorie/deployment/profiles/default/registry.xml
src/euphorie/upgrade/deployment/configure.zcml
src/euphorie/upgrade/deployment/v18/20250521110138_fix_default_language/upgrade.py
versions-6.1.cfg

When installing Euphorie the default language is set to en-us. This language is not listed in the available languages. This can cause the site to return errors when creating new objects that contain the language field.

Fix the default language when installing Euphorie

---

news/3574.bugfix
src/euphorie/client/browser/templates/status_info.pt

Fix wording (“unpublished” → “unlocked”)

---

news/3645.feature
src/euphorie/client/browser/webhelpers.py

Don't show training at all in the client if disabled on the tool

---

news/3709.bugfix
src/euphorie/client/browser/templates/register_session.pt

Fix registration form on @@register_session

---

news/3800.bugfix.rst
src/euphorie/client/survey.py
src/euphorie/client/tests/test_report.py

Fixes an issue for archived sessions when the survey is republished with a removed risk. Refs https://github.com/syslabcom/scrum/issues/3800

PPT generation is more resilient

---

news/3573.bugfix
src/euphorie/client/browser/templates/report_landing.pt
src/euphorie/client/browser/templates/sharing_badge.pt

Refs: https://github.com/syslabcom/scrum/issues/3573

Replace Twitter icon with X icon
