docs/changes.rst, src/euphorie/content/dependency.py, src/euphorie/content/module.py, src/euphorie/content/survey.py
Allow conditional fields (that are only visible via NuPlone's Dependency) to be marked as required. A custom validator then checks if the condition is met before raising a missing value error.
=> Conditional validation

src/euphorie/testing.py
Like zope.conf does for regular instances
=> Set the test publisher encoding to utf-8

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/survey.py, src/euphorie/client/browser/templates/publication_menu.pt, src/euphorie/client/browser/templates/start.pt, src/euphorie/client/model.py, src/euphorie/client/templates/sessions.pt, src/euphorie/client/tests/test_functional_login.py, src/euphorie/client/tests/test_survey_integration.py, src/euphorie/testing.py
This PR adds two views:
- `publication_menu`
- `publication_date`
The publication menu is used to display the tooltip with the form to publish/refresh/unpublish the survey session.
The publication_date is the endpoint for the publication menu form action.
This feature is toggled off in the UI and can be turned on by providing a `publication_badge` traversable that loads the tooltip.
=> Manage and display the survey publication date

docs/changes.rst, src/euphorie/client/authentication.py, src/euphorie/client/tests/test_authentication.py, src/euphorie/client/tests/test_functional_authentication.py, src/euphorie/client/tests/test_settings.py
Let the Euphorie PAS plugin only handle requests from with the client
=> Plone5: PAS Plugin fix

docs/changes.rst, setup.py, src/euphorie/client/browser/country.py, src/euphorie/client/browser/templates/new-session-test.pt, src/euphorie/client/browser/templates/new-session.pt, src/euphorie/content/behaviors/__init__.py, src/euphorie/content/behaviors/configure.zcml, src/euphorie/content/behaviors/toolcategory.py, src/euphorie/content/configure.zcml, src/euphorie/content/export.py, src/euphorie/content/profiles/default/registry/vocabularies.xml, src/euphorie/content/upload.py, src/euphorie/content/vocabularies.py, src/euphorie/deployment/profiles/default/metadata.xml, src/euphorie/deployment/upgrade/configure.zcml, src/euphorie/deployment/upgrade/profiles.zcml, src/euphorie/deployment/upgrade/profiles/to_0022/registry.xml, versions.cfg
New behavior for Survey that makes it possible to assign one or more categories to it. If set, the "new session" modal in the client will display that survey under its categories.
TODO:
-  [x]  adjust "new test session" modal
=> Plone5 categorised Survey templates

setup.py, src/euphorie/client/subscribers/configure.zcml, src/euphorie/client/subscribers/imagecropping.py
Concept taken from staralliance.whiteside
Use case: crop main image on Survey, Module and Risk to scale that is needed in the
Training module. Enabling this currently happens as proof-of-concept in oira.daimler
=> Add subscriber that auto-crops images in given scales

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/webhelpers.py, src/euphorie/client/tests/test_utils.py, src/euphorie/client/utils.py
Added a ploneintranet inspired @@date-picker-i18n.json view that can be used
to provide translations for the calendar picker.
Example usage:
```
<input class="pat-date-picker"
data-pat-date-picker="...; i18n: ${portal_url}/@@date-picker-i18n.json; ..."
/>
```
=> Date picker i18n

docs/changes.rst, src/euphorie/client/profile.py
All optional modules default to "skip". The user needs to actively decide that the module is relevant for them.
=> Fix for initial state of optional modules

src/euphorie/client/browser/webhelpers.py, src/euphorie/client/tests/test_webhelpers.py
Reason: the default behaviour is that sessions are always filtered according
to the current user and maybe also to his group.
But we have use-cases where we don't want to perform any filtering by
account.
@ale-rt I know this approach is quite minimalistic. But I don't (yet) see a use-case for passing in an actual account, so I think a boolean is enough.
=> Enhance the get_sessions_query method by a new param: filter_by_account

src/euphorie/client/browser/webhelpers.py, src/euphorie/client/model.py, src/euphorie/client/tests/test_model.py, src/euphorie/client/tests/test_webhelpers.py
BREAKING CHANGE: the include_group parameter is removed and replaced
with filter_by_group parameter which has more flexibility
This PR makes it possible to optionally filter sessions by account or group,
it is also possible to filter for lists of users or groups.
Refs. and replaces #224
=> feat: better account and group filters

src/euphorie/client/browser/webhelpers.py
This is useful for custom OiRA installations that might override the sessions model
=> Allow to modify the session table

src/euphorie/client/browser/login.py, src/euphorie/client/browser/session.py, src/euphorie/client/browser/webhelpers.py, src/euphorie/client/conditions.py, src/euphorie/client/country.py, src/euphorie/client/model.py, src/euphorie/client/settings.py
We have seen the using `getSecurityManager().getUser()`, which _should_ return the current `model.Account` can lead to unexpected results in registration and conversion of guest accounts.
=> Rework login

docs/changes.rst, src/euphorie/client/browser/templates/publication_menu.pt, src/euphorie/client/browser/templates/session-browser-sidebar.pt, src/euphorie/client/browser/templates/tool_sessions.pt, src/euphorie/client/browser/webhelpers.py
In all locations where we use pat-display-time, make sure that the datetime used for it has a timezone set.
We fetch the timezone to be used from the host (server).
=> Use timezone-aware dates for pat-display-time

docs/changes.rst, src/euphorie/client/browser/session.py, src/euphorie/client/model.py, src/euphorie/client/update.py
Make sure that an update to the title of a module or risk gets propagated to existing sessions.
=> Propage title changes on risks/modules

docs/changes.rst, src/euphorie/client/browser/module.py, src/euphorie/client/browser/risk.py, src/euphorie/client/interfaces.py, src/euphorie/client/subscribers/configure.zcml, src/euphorie/client/subscribers/module.py
In the wild it sometimes happens that the order of omega risks gets jumbled. The reason has not been found (heisenbug).
With an event handler we can make sure that after adding or removing an omega risk the original order is restored. Additionally we close any gaps in numbering that might arise if a risk gets deleted.
=> Omega risks: fix order

docs/changes.rst, src/euphorie/deployment/browser/configure.zcml, src/euphorie/deployment/browser/site.py, src/euphorie/deployment/tests/test_setup.py
A new view ``@@get-resources-timestamp`` has been introduced to not use
the protected view ``@@refresh-resources-timestamp`` which will be
forbidden by the latest security hotfix
=> Add a new view @@get-resources-timestamp

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/templates/help-menu.pt, src/euphorie/client/browser/templates/shell-for-iframe.pt, src/euphorie/client/browser/templates/shell.pt, src/euphorie/client/browser/templates/user-menu.pt
- Remove obsolete ``__patternslib_public_path__`` global JavaScript variable. The public path and chunk directory is automatically discovered.
- Remove Login/Registrations menus from unauth toolbar - aligned with prototype.
- Integrate help menu.
Ref: scr-1198
=> scr-1198 - portal renewal: main template website border

src/euphorie/client/browser/login.py, src/euphorie/client/browser/settings.py, src/euphorie/client/tests/test_authentication.py
“The password needs to be at least 12 characters long and needs to contain at least one lower case letter, one upper case letter and one digit.”
Refs SCR-1388
=> Enforce client password policy

docs/changes.rst, src/euphorie/client/authentication.py
Other plugins follow the same logic, see e.g.:
https://github.com/euphorie/Euphorie/commit/6f20f60dc4c52287c68f4ad72951672a22a63640
=> The euphorie user factory plugin is enabled now only in the client

src/euphorie/client/browser/login.py, src/euphorie/client/subscribers/configure.zcml, src/euphorie/client/subscribers/login.py, src/euphorie/client/tests/test_functional_login.py
A short discussion on this...
For some reason the authentication process for the client does not fire the user logged in event.
In the previous PR I then just recorded login time in the login view.
Anyway there might be other projects that override that view or use different authentication methods.
Having a subscriber is then a more compatible and secure way to have the last login time recorded.
=> Add a subscriber to record the last login for a client account.

docs/changes.rst, scripts/proto2diazo.py, src/euphorie/client/browser/country.py, src/euphorie/client/browser/login.py, src/euphorie/client/browser/survey.py, src/euphorie/client/tests/test_authentication.py, src/euphorie/upgrade/content/v1/20210730081303_add_lead_image_behavior_to_survey/upgrade.py
Login/Registration: Use webhelpers to get country URL. Fixes redirect to default country when came_from is missing.
Refs [SCR-1586](https://jira.syslab.com/browse/SCR-1586)
=> Keep country after registration

docs/changes.rst, src/euphorie/client/browser/publish.py, src/euphorie/client/browser/templates/publish.pt
Show a warning when republishing a tool with changed structure.
Note: Added modules/risks are not considered a significant change. Only removed items are warned about.
Refs SCR-1600
=> Warning about changed structure

docs/changes.rst, src/euphorie/client/browser/session.py, src/euphorie/client/browser/templates/profile.pt
Profile page: if none of the profile questions uses the location question, do not show the intro text that informs about multiple locations
Refs: #SCR-1683
=> Adjust instructions on Profile page to actual situation

docs/changes.rst, src/euphorie/client/browser/risk.py, src/euphorie/client/browser/session.py, src/euphorie/client/model.py, src/euphorie/client/tests/test_cloning.py, src/euphorie/client/tests/test_risk.py
When a user tries to clone a session without enough rights,
they are redirected to the sessions overview
=> Improve the clone functionality

docs/changes.rst, src/euphorie/client/browser/reset_password.py, src/euphorie/client/browser/templates/password_recovery_email.pt
Password reset: Only use X-Forwarded-For if it contains an IP address. Fixes email tampering attack.
Refs syslabcom/scrum#158
=> Password reset: Fix email tampering

src/euphorie/client/browser/session.py, src/euphorie/client/browser/settings.py, src/euphorie/client/browser/templates/new-session.pt, src/euphorie/client/browser/templates/portlet-available-tools.pt, src/euphorie/client/browser/templates/start.pt, src/euphorie/content/overrides.zcml, src/euphorie/content/protect.py
Make CSRF protection kick in if SQL data is being written.
This is a little hacky because `safeWrite` doesn't work for the objects that are added (they have no _p_oid).
The tests do pass but there could of course still be some false positives of the CSRF protection. I would only expect a `@@confirm-action` redirect in this case, but maybe it pays off to do some more thorough manual testing.
Refs syslabcom/scrum#158
=> CSRF for SQL writes

docs/changes.rst, src/euphorie/content/browser/export.py, src/euphorie/content/browser/upload.py, src/euphorie/content/tests/test_export.py
When a tool editor wants to export an OiRA tool as XML, they now have the option to de-select certain element, such as images or legal texts, so that the tool export is useful for translation.
Additionally, a text-only version can be included in the export, so that a simple word count will be possible. This is useful for translators.
See https://github.com/syslabcom/scrum/issues/147
=> XML export enhancement

src/euphorie/client/browser/training.py
Get objects directly. Catalog doesn't return them.
I didn't debug much further, but it's not a permission issue. I think the questions are just not indexed on the client side.
Refs syslabcom/scrum#195
=> Training questions: Fix empty list

setup.py, src/euphorie/content/browser/export.py, src/euphorie/content/browser/upload.py, src/euphorie/content/tests/test_export.py, src/euphorie/content/tests/test_functional_upload.py
Add support for exporting and importing in an XML format which the eTranslation service can handle without losing tool configuration settings or (much) formatting.
Refs https://github.com/syslabcom/scrum/issues/269
=> 269 eTranslation export and import

docs/changes.rst, src/euphorie/client/browser/risk.py
Action plan: Defer translations until language negotiation is finished.
Refs syslabcom/scrum#251
=> Fix translation of confirmation/validation messages

docs/changes.rst, src/euphorie/client/browser/reset_password.py, src/euphorie/client/browser/templates/password_recovery_email.pt, src/euphorie/client/setuphandlers.py, src/euphorie/client/tests/test_functional_login.py, src/euphorie/upgrade/client/v1/20220622072638_set_password_expiration_timeout/upgrade.py
Invalidate password reset after 12 hours, when a new reset is requested, or when it has been used, respectively.
Refs syslabcom/scrum#241
=> Harden password reset

docs/changes.rst, src/euphorie/client/browser/country.py
Assuming that `categories == None`, the second `if` in:
```
if not isinstance(categories, list):		
categories = [categories]		
if not categories:		                if not categories:
categories = ["None"]
```
was never entered.
That caused `categories` to be modified in the end to `[None]`.
Then sorting:
```
return sorted(survey_items, key=lambda x: (x[0], x[1].title))
```
would fail with:
```
TypeError: '<' not supported between instances of 'str' and 'NoneType
```
=> Fix the way get_survey_templates handles a survey with an unset category

docs/changes.rst, src/euphorie/client/browser/session.py, src/euphorie/client/model.py, src/euphorie/client/tests/test_update.py
Change type of measure in session if it is deleted in ZODB so that it stays visible in the client.
Refs syslabcom/scrum#351
=> Convert deleted measures

docs/changes.rst, src/euphorie/client/browser/webhelpers.py, src/euphorie/client/tests/test_webhelpers.py
Also made it possible to override the list of available tabs.
Refs syslabcom/scrum#497 euphorie/Euphorie#379
=> Improved get_dashboard_tab

docs/changes.rst, src/euphorie/client/browser/risk.py
Transform risk notes (comment field) to safe HTML when saving.
Refs syslabcom/scrum#444
=> Comment: safe html

src/euphorie/client/browser/templates/sessions-dashboard.pt, src/euphorie/client/browser/templates/shell.pt, src/euphorie/client/browser/templates/training.pt, src/euphorie/deployment/tiles/templates/usermgmt-tree.pt
Use explicit pat-navigation trigger class on navigation elements which were pre Patternslib 9.2 also initialized.
=> pat-navigation updates

src/euphorie/deployment/profiles/default/rolemap.xml
That is the default, there is no need for this redundant setting
=> Remove the rolemap assignment for Zope2.Public

docs/changes.rst, src/euphorie/client/browser/configure.zcml, src/euphorie/deployment/setuphandlers.py, src/euphorie/testing.py
This [restores a line of code](https://github.com/euphorie/Euphorie/pull/461/files#diff-9687043f5fc4f5ff7e02e6778821127d070d35ee7d1c22e59d1cc50d155ebf4bL123) in the setup handler that publishes the client folder.
That line has been present for years and it is indeed needed for the application to work at all.
It was probably commented because the switch to the Plone 5 default test layer did not included setting up a default workflow chain.
This is now done in https://github.com/euphorie/Euphorie/pull/461/files#diff-972db14e3a8d2a845681d1db32e486a080300af841abac8d99d3d43181f3eb64R77-R78
With this change the test pass even if the "surveys" view is protected by the `zope2.View` permission, which is what we want to not leak unwanted informations.
=> Sanitize the permissions handling in the client section

docs/changes.rst, src/euphorie/client/browser/training.py
=> Disable the cache control settings on the certificate pages

docs/changes.rst, src/euphorie/client/browser/templates/risk_identification_custom.pt, src/euphorie/client/browser/templates/webhelpers.pt
Fixes: https://github.com/syslabcom/scrum/issues/688
This handles two cases, one for custom risks and one for standard risks. Evaluating the source of Euphorie, it seems that the custom risk is always used, unless there are some overrides in Euphorie policy add-ons.
=> Fix a padding issue in the risk evaluation template.

docs/changes.rst, src/euphorie/client/browser/country.py, src/euphorie/client/browser/templates/portlet-available-tools.pt, src/euphorie/client/browser/templates/portlet-my-ras.pt, src/euphorie/client/browser/templates/portlet-my-trainings.pt, src/euphorie/client/browser/templates/sessions-dashboard.pt, src/euphorie/client/browser/training.py, src/euphorie/client/tests/stories/ForgotPassword.txt, src/euphorie/client/tests/test_functional_client.py, src/euphorie/client/tests/test_functional_country.py, src/euphorie/client/tests/test_functional_profile.py, src/euphorie/client/tests/test_functional_report.py, src/euphorie/client/tests/test_functional_risk.py
See also https://github.com/syslabcom/oira.prototype/pull/402
Replaces #488
In #488 @thet noticed this:
> Please note: any request parameters would get lost when calling the @@dashboard view.
I found that request parameters were only set by `portlet-my-ras` which contains a form for toggling the display of archived items. It was re-injecting the whole dashboard. Now it only injects itself; therefore the dashboard does not need to be aware of request parameters.
For variants with custom dashboards like daimler we need to double check that the portlets also only re-inject themselves.
syslabcom/scrum#712
=> Lazy-load the dashboard portlets

src/euphorie/client/browser/training.py
The change in https://github.com/euphorie/Euphorie/pull/500 was breaking subclasses of the training view.
=> training view: re-add measures key in slide_contents.

docs/changes.rst, src/euphorie/client/docx/compiler.py, src/euphorie/client/docx/html.py, src/euphorie/content/browser/survey.py
This involves an API change: Instantiate HtmlToWord compiler freshly for each document and make use of oject orientated encapsulation. Also do not call the compiler but create a dedicated compile_inline method.
This fixes a problem where a bullet number counter was not reset among multiple docx compilations, resulting in different documents for the same report when downloaded multiple times.
=> HtmlToWord: Fix problem with different documents for each report compilation

docs/changes.rst, src/euphorie/client/browser/templates/password_recovery_email.pt
It does not work when generated on a session because of the custom traversal.
syslabcom/scrum#1026
=> Generate password reset link on country or client

docs/changes.rst, src/euphorie/client/browser/templates/sessions-dashboard.pt, src/euphorie/client/browser/training.py
Turns out there are optional portlets (see also https://gitlab.com/syslabcom/daimler/daimler.oira/-/merge_requests/191)
[Ignore whitespace](https://github.com/euphorie/Euphorie/pull/507/files?diff=split&w=1) when viewing diff.
https://github.com/syslabcom/scrum/issues/1027
https://github.com/syslabcom/scrum/issues/712
=> Dashboard: Don't try to inject empty portlets

docs/changes.rst, src/euphorie/client/browser/webhelpers.py, src/euphorie/client/tests/test_webhelpers.py
- Survey navigation: When survey is archived or otherwise disabled the report,
training and status menu items should still be active.
- Survey navigation: Fix class when navigation menu is active and disabled to
not render as "activedisabled".
=> Fix survey navigation

src/euphorie/client/adapters/session_traversal.py, src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/error.py, src/euphorie/client/browser/session.py, src/euphorie/client/model.py, src/euphorie/deployment/upgrade/alembic/versions/20230406070728_add_session_redirect.py, src/euphorie/upgrade/deployment/v1/20230406070728_add_session_redirect/upgrade.py
This currently keeps the URL with the old session ID. I'd rather do a redirect to the URL with the new ID but I can't figure out how to do that in a namespace traversal. `response.redirect()` just gives me a blank page, `raise Redirect` gives me a traceback. Any ideas?
syslabcom/scrum#833
=> Keep session URL usable when tool is updated

docs/changes.rst, src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/organisation.py, src/euphorie/client/browser/templates/confirm-organisation-invite.pt, src/euphorie/client/tests/test_organisations.py
Note that this removes the permission check on the organisation logo view because the design implies that a user should see the logo even if they're not yet a member of the organisation.
syslabcom/scrum#594
=> Ask for confirmation when following an organisation invite link

docs/changes.rst, src/euphorie/client/browser/templates/webhelpers.pt
Do not display the note "The risk evaluation has been automatically done by the tool" if there is an integrated action plan
=> Add a condition to display a note

src/euphorie/client/browser/organisation.py
Follow-up of #539 
Deployment postponed because translations are missing.
syslabcom/scrum#1133
=> Deactivate organisation invite confirmation mail

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/consultancy.py, src/euphorie/client/browser/risk.py, src/euphorie/client/browser/templates/consultancy.pt, src/euphorie/client/browser/templates/panel-request-validation.pt, src/euphorie/client/browser/webhelpers.py, src/euphorie/client/tests/test_webhelpers.py, src/euphorie/deployment/profiles/default/registry.xml, src/euphorie/upgrade/deployment/v1/20230421104953_add_use_consultancy_phase_feature_switch/registry.xml, src/euphorie/upgrade/deployment/v1/20230421104953_add_use_consultancy_phase_feature_switch/upgrade.py
The new step is by default deactivated by the feature switch `euphorie.use_consultancy_phase`.
The following PRs build on this one and on one another:
* implement validation request https://github.com/euphorie/Euphorie/pull/536
* actual validation by consultant https://github.com/euphorie/Euphorie/pull/537
* refactor & fixes https://github.com/euphorie/Euphorie/pull/538
If you prefer you can review and merge the whole package (#538) and disregard the other PRs.
To do in further PRs:
* populate link “Find an OSH consultant”
syslabcom/scrum#1105
=> Add step “Consultancy” to session

src/euphorie/content/browser/export.py, src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/euphorie.pot, src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po
Label `label_is_etranslate_compatible` has conflicting defaults, compare `content/browser/upload.py` and `content/browser/export.py`
=> Split up conflicting labels for etranslate import/export

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/consultancy.py, src/euphorie/client/browser/templates/notify-assessment-validated.pt, src/euphorie/client/browser/templates/panel-validate-risk-assessment.pt, src/euphorie/client/tests/test_consultancy.py
Includes #533 and #536, merge those first
This is missing the final step of locking the risk assessment to indicate that it has been validated, to be added when syslabcom/scrum#1097 is implemented.
=> Implement validation by consultant

Makefile, docs/changes.rst
Add and commit generated resources from "resources-install" and  "update-patterns" targets.
For "make resources-install" add the prototype commit id to a new PROTOTYPE_COMMIT_ID file and the commit message.
For "make update-patterns" add the Patternslib version to the commit message.
=> Makefile resource update: Improve reproducibility.

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/consultancy.py, src/euphorie/client/browser/templates/consultancy.pt, src/euphorie/client/model.py, src/euphorie/client/tests/test_consultancy.py, src/euphorie/deployment/upgrade/alembic/versions/20230502091628_upgrade_consultancy_table.py, src/euphorie/upgrade/deployment/v1/20230502091628_upgrade_consultancy_table/upgrade.py
Original plan was to treat a locked session with a consultant assigned as validated, but we need to support locking sessions independently of validation status.
This also means that the sqlalchemy declaration via `Table` doesn't work any more because the association needs the extra column `status`.
=> Validation: Record status of validation

src/euphorie/client/browser/consultancy.py, src/euphorie/client/browser/templates/notify-request-validation.pt
I am resurrecting #545 because I still see that the mail sent looks like:
```
Dear b@example.com,
Ale requested to validate the risk assessment &lsquo;COVID-19 revision&rsquo;.
Please click on the link below to visit the risk assessment. If you approve of the contents of the risk assessment, then please click on &lsquo;Validate&rsquo; in the section &lsquo;Consultancy&rsquo; to give the risk assessment an official validated status.
http://localhost:9110/Plone/client/eu/covid-19/covid-19-revision/++session++2/@@start
```
That happens because zpretty escaped the quote characters.
Either we make zpretty ignore that file or we change zpretty to not do that substitution or we do it like proposed in this PR.
=> Fix some bits in the email top the consultant

src/euphorie/client/browser/consultancy.py, src/euphorie/client/browser/templates/consultancy.pt
It might make sense to hide the whole consultancy form, or only display a note that an admin can do the consultancy stuff, but hiding the buttons if a user can't use them is already a step in the right direction.
syslabcom/scrum#1105
=> Hide elements for requesting validation and adding users from non-admins

Makefile
Fixes make on nixos where /bin/bash does not exist
=> Makefile: Use env to run bash

docs/changes.rst, src/euphorie/client/browser/templates/webhelpers.pt
=> Fix selected measure text spanning whole page instead of bein shown in training module.

src/euphorie/client/browser/configure.zcml, src/euphorie/client/browser/templates/new-session.pt, src/euphorie/client/browser/templates/surveys.pt, src/euphorie/client/browser/templates/tool_sessions.pt
Also use updated modal when starting a new session from the tools section
Note: there is one quirk - when calling the new-session modal on a sector (which does not happen in the current code) and passing the tool (survey) as a request parameter, you can select all sessions from the sector, not only those from the tool. Not fixing because the current code does not do that and sectors mostly only have one tool.
syslabcom/scrum#1137
=> Duplication: Tools Section

src/euphorie/client/model.py
fixes `AttributeError: strategy` in many queries
```
2023-06-16 07:37:50,799 ERROR   [Zope.SiteErrorLog:252][waitress-2] 1686893870.79906680.901494409626681 http://oira.local:4080/Plone2/client/eu/test-guy/risk-titles-1141/++session++55690/@@oira-report.docx
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module ZPublisher.WSGIPublisher, line 280, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 63, in call_object
Module euphorie.client.docx.views, line 168, in __call__
Module euphorie.client.docx.views, line 43, in get_payload
Module euphorie.client.docx.views, line 291, in get_data
Module euphorie.client.docx.views, line 260, in …
```
=> Call configure_mappers() in instrumentation

docs/changes.rst, src/euphorie/client/model.py
Add some alias in exists query.
Remove the need to delete from the scope the aliased instances by using factory methods.
Fixes #609.
=> Use aliases in exists queries

src/euphorie/content/browser/configure.zcml
Given in Plone 6 it is a browser view and not a script
=> Custom prefs_main_template view needs a layer in Plone 6

src/euphorie/client/model.py
Fixes:
```
sqlalchemy.exc.ProgrammingError: sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'Row'
```
The problem happened because the filter was mixing up an integer id and a Row object .
```
((Pdb)) account_ids
{3, (32276,)}
((Pdb)) tuple(account_ids)[1].owner_id
32276
```
=> Fix heterogeneous query

Makefile
I'd like to be able to run `make pot` without running buildout first. I can take care of installing i18ndude myself.
=> Makefile: No dependency for target `pot`

docs/changes.rst, src/euphorie/client/utils.py
It causes this error:
```
Module euphorie.client.browser.organisation, line 445, in
notify_inviter
Module <decorator-gen-3>, line 2, in send_email
Module plone.api.validation, line 81, in wrapped
Module plone.api.portal, line 198, in send_email
Module Products.MailHost.MailHost, line 215, in send
Module Products.MailHost.MailHost, line 337, in _send
Module zope.sendmail.delivery, line 141, in send
ValueError: Malformed Message-Id header
```
=> Remove the Message-Id header

src/euphorie/client/docx/compiler.py
It throws an error when a measure has no plan_type attribute
Refs https://github.com/syslabcom/scrum/issues/1508
=> Fix download a tool preview

docs/changes.rst, src/euphorie/client/browser/templates/tool_sessions.pt
Compare proto: https://oira.cornelis.amsterdam/tools/commerce-de-gros-no-alimentaire
syslabcom/scrum#1555
=> Remove broken lock icon from tool info page

docs/changes.rst, src/euphorie/client/docx/compiler.py
* translate page number cell in footer
* add icon for unanswered risks
* add risk number to title
* add space before additional measure info
syslabcom/scrum#1295
=> Short report tweaks

src/euphorie/client/docx/compiler.py
Keep top/bottom cell borders between risks of same module.
syslabcom/scrum#1295
=> More short report tweaks.

docs/changes.rst, src/euphorie/client/browser/country.py
Fix an error with a fresh database and no sessions yet.
The sidebar error led to other errors like the "Fremdfirmenkoordination" dropdown not being usable.
This was the traceback:
```
2023-10-20 12:21:35,852 ERROR   [Zope.SiteErrorLog:252][waitress-1] 1697797295.85126830.0008442311837014715 http://localhost:9090/Plone/client/de/view
Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 176, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 385, in publish_module
Module ZPublisher.WSGIPublisher, line 280, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 63, in call_object
Module daimler.oira.client.browser.country, line 89, in __call__
Module euphorie.client.browser.country, line 274, in __call__ …
```
=> Fix sidebar error when there is no root group.

docs/changes.rst, src/euphorie/content/browser/configure.zcml, src/euphorie/content/browser/survey.py, src/euphorie/content/browser/templates/find-solution-title-duplications.pt
=> Add View find-solution-title-duplications

docs/changes.rst, src/euphorie/deployment/products.py
Fix error when freshly installing a Plone site where `getNonInstallableProfiles` is missing.
Ref: https://github.com/plone/Products.CMFPlone/issues/3862
=> Fix error when freshly installing a Plone site

docs/changes.rst, src/euphorie/client/browser/training.py, src/euphorie/client/tests/test_training__hide_from_training.py, src/euphorie/content/behaviors/configure.zcml, src/euphorie/content/behaviors/hide_from_training.py, src/euphorie/content/browser/export.py, src/euphorie/content/browser/upload.py, src/euphorie/content/tests/test_functional_module.py
Ref: scrum-1573
Merge together:
https://github.com/euphorie/Euphorie/pull/669
https://github.com/syslabcom/daimler.oira/pull/248
=> Add behavior to hide modules from trainings.

src/euphorie/client/notifications/notification__ra_not_modified.py, src/euphorie/client/tests/test_notifications.py, src/euphorie/deployment/locales/bg/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/ca/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/cs/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/da/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/el/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/en/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/es/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/et/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/euphorie.pot, src/euphorie/deployment/locales/fi/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/hr/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/hu/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/is/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/it/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/lt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/lv/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/mt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/no/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/pl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/pt/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/ro/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sv/LC_MESSAGES/euphorie.po
This removes the session title references, removes wording which references the title in the subject and introduces some plural forms.
Note: i18ndude cannot extract the plural forms. So currently only the plural default message is used. There is no problem with the singular form.
See: https://github.com/collective/i18ndude/issues/112
=> Notifications: translation fixes and updates

src/euphorie/client/notifications/base.py
=> Notifications: Don't send mail if recipient has no email address.

docs/changes.rst, src/euphorie/client/browser/error.py
This saves the log from this stuff:
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/srv/s-oira/.buildout/eggs/cp38/Zope-4.8.10-py3.8.egg/ZPublisher/WSGIPublisher.py", line 176, in transaction_pubevents
yield
File "/srv/s-oira/.buildout/eggs/cp38/Zope-4.8.10-py3.8.egg/ZPublisher/WSGIPublisher.py", line 385, in publish_module
response = _publish(request, new_mod_info)
File "/srv/s-oira/.buildout/eggs/cp38/Zope-4.8.10-py3.8.egg/ZPublisher/WSGIPublisher.py", line 264, in publish
obj = request.traverse(path, validated_hook=validate_user)
File "/srv/s-oira/.buildout/eggs/cp38/Zope-4.8.10-py3.8.egg/ZPublisher/BaseRequest.py", line 535, in traverse
return response.notFoundError(URL)
File …
```
=> Do not log anymore not found exceptions

src/euphorie/content/vocabularies.py
There can easily be an empty row at the end.
=> RegistryValueVocabulary: filter out empty values.

docs/changes.rst, src/euphorie/client/browser/login.py
Touch the sessions before that to remove the reference to the guest account in `last_modifier_id` column.
Fixes syslabcom/scrum#2155
=> Delete guest account after sessions have been transferred.

src/euphorie/upgrade/deployment/v1/20240423105626_clean_up_last_modifier_id/upgrade.py
In acc2353126 (#719) we changed `transferGuestSession` to update `last_modifier_id` and delete the guest account after all sessions have been transferred. This upgrade step does a similar thing with existing sessions. We don't update the modification date because we don't know when the session was transferred. We also double check that the guest account doesn't have any sessions associated with it so that we can safely delete it.
Fixes syslabcom/scrum#2155
=> Clean up references to guest accounts in last_modifier_id

src/euphorie/client/browser/certificates.py, src/euphorie/client/browser/templates/training_certificate_inner.pt, src/euphorie/client/browser/templates/training_certificate_view.pt, src/euphorie/client/browser/training.py
The training certificate view was previously meant to only show the current user's certificates. Now it can take a parameter `training_id` that makes it display the training with the given id instead. The default is still to show the current user's certificate connected to the respective session (there can be only one such certificate per session). The parameter can also be passed to the `index()` method so that we don't have to fiddle with the request when displaying multiple certificates like in the overview page.
Ref syslabcom/scrum#2142
=> Show training certificates from other users in my organisation

docs/changes.rst, src/euphorie/client/browser/templates/training_certificate_inner.pt, src/euphorie/client/browser/training.py
Compare https://github.com/euphorie/Euphorie/blob/scrum-2142-certificate-logo/src/euphorie/client/browser/templates/organisation.pt#L87
Ref syslabcom/scrum#2142
=> Show organisation logo on training certificate

src/euphorie/client/browser/certificates.py, src/euphorie/client/browser/templates/training_certificate_inner.pt, src/euphorie/client/browser/templates/training_certificate_view.pt, src/euphorie/client/browser/training.py
Contains #731 
Ref https://github.com/syslabcom/scrum/issues/2143
=> Show certificates in reverse chronological order

buildout.cfg, setup.py
In Plone 5.2 this is empty and in 6.0 it does not exist. No longer use `allow-unknown-extras` in our `buildout.cfg`.  That hides the error on install.
=> Do not pull in plone.namedfile[blobs].

src/euphorie/content/browser/templates/minimal_main_template.pt
Otherwise in the overview-controlpanel pn Plone 6 you get:
NameError: name 'icons' is not defined
With the new line, on Plone 5 the iconresolver view won't be found, so `icons` will be None. This is fine because icons is not used on Plone 5.
=> Define icons view in minimal main template.

docs/changes.rst, src/euphorie/content/configure.zcml, src/euphorie/content/dependency.py
The fields were introduced in:
- https://github.com/euphorie/Euphorie/pull/115/files
Refs.:
- https://github.com/syslabcom/scrum/issues/2615
=> The conditional fields have now widgets that can be customized as needed

docs/changes.rst, src/euphorie/content/browser/configure.zcml, src/euphorie/content/browser/similar_titles.py, src/euphorie/content/browser/templates/similar_titles.pt, src/euphorie/content/browser/templates/similar_titles_results.pt
Note that the minimum and maximum similarity values are not stored. When you call the view the default values are displayed (0.5 and 1.0, resp.) but they may not match the results that are shown. I would say that's OK for now, but could be a possible future improvement.
Ref syslabcom/scrum#2517
=> Similar titles: Store HTML as annotation until new search is triggered

docs/changes.rst, src/euphorie/client/model.py
=> Fix query for unanswered risks

docs/changes.rst, src/euphorie/content/tests/stories/CopyFromOtherSector.txt, src/euphorie/deployment/profiles/default/registry.xml, src/euphorie/upgrade/deployment/v1/20241127135848_fix_navigation_in_cms/registry.xml, src/euphorie/upgrade/deployment/v1/20241127135848_fix_navigation_in_cms/upgrade.py
Fix the plone.displayed_types registry record that was previously only updated  through upgrade steps, see:
- https://github.com/euphorie/Euphorie/blob/7fb70908f120554c9395a3bc6740053acf38a414/src/euphorie/deployment/upgrade/profiles/to_0020/registry.xml#L7
- https://github.com/euphorie/Euphorie/blob/7fb70908f120554c9395a3bc6740053acf38a414/src/euphorie/upgrade/deployment/v1/20220318135716_add_training_question/registry.xml#L7
This fixes the navigation on the CMS side for freshly installed sites and for sites that have been deployed with recent versions of the package.
=> Fix the CMS navigation

docs/changes.rst, src/euphorie/client/model.py
...from ZODB
Ref https://github.com/syslabcom/scrum/issues/3038
=> Don't update titles of session-specific instances of profilequestions

docs/changes.rst, src/euphorie/client/notifications/notification__ra_not_modified.py, src/euphorie/client/tests/test_notifications.py
This makes sure the context filter is used by which any sessions of depublished tools are excluded.
Ref https://github.com/syslabcom/scrum/issues/3024
=> Notifications: Use `webhelpers.get_sessions_query()`

docs/changes.rst, src/euphorie/client/browser/templates/assessments.pt, src/euphorie/client/browser/templates/certificates.pt, src/euphorie/client/browser/templates/module_identification_custom.pt, src/euphorie/client/browser/templates/more_menu.pt, src/euphorie/client/browser/templates/new-session.pt, src/euphorie/client/browser/templates/portlet-available-tools.pt, src/euphorie/client/browser/templates/portlet-my-ras.pt, src/euphorie/client/browser/templates/report.pt, src/euphorie/client/browser/templates/start.pt, src/euphorie/client/browser/templates/webhelpers.pt, src/euphorie/client/tests/test_functional_country.py, src/euphorie/content/utils.py, src/euphorie/deployment/locales/de/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/fr/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/sk/LC_MESSAGES/euphorie.po
I did a session with Daniel today and aligned markup with proto so that we are better prepared for the upcoming usability testing. 
These changes should be merged together with the PR to update the resources to the latest version - see https://github.com/euphorie/Euphorie/pull/792 (but is not directly coupled). The fixes are safe, and also work with an older version. Also, the proto update is safe, we clicked through, there was no visible breakage.
=> Markup alignment for usability testing

docs/changes.rst, src/euphorie/client/browser/templates/training.pt, src/euphorie/client/browser/training.py
=> Don't allow editing training slides when user doesn't have edit permission on the session

src/euphorie/client/authentication.py, src/euphorie/client/browser/country.py, src/euphorie/client/browser/risk.py, src/euphorie/client/browser/training.py, src/euphorie/client/docx/views.py, src/euphorie/client/enum.py, src/euphorie/client/mails/base.py, src/euphorie/client/model.py, src/euphorie/client/tests/stories/ChangeEmail.txt, src/euphorie/client/tests/test_risk.py, src/euphorie/content/browser/export.py, src/euphorie/content/browser/upload.py, src/euphorie/content/solution.py, src/euphorie/content/tests/test_export.py, src/euphorie/content/utils.py, src/euphorie/deployment/browser/search.py, src/euphorie/deployment/commands/xmlimport.py, src/euphorie/deployment/tests/test_setup.py
Some `safe_text` calls could be removed, but I think this is out of the scope for this PR.
=> Remove deprecated imports

src/euphorie/deployment/browser/configure.zcml, src/euphorie/deployment/browser/maintenance.py, src/euphorie/deployment/browser/templates/maintenance.pt, src/euphorie/upgrade/deployment/v1/20250327125832_install_the_maintenance_actions/actions.xml, src/euphorie/upgrade/deployment/v1/20250327125832_install_the_maintenance_actions/upgrade.py
The view uses the actions defined in the newly introduced maintenance_actions category to be customizable per project. Some default actions are expected to land in the code after a first test phase.
Refs. https://github.com/syslabcom/scrum/issues/3197
=> Add the admin-maintenance view

news/3384.fix.rst, src/euphorie/client/browser/templates/surveys.pt
When on the tools overview, there is no need to have the selection modal, as users click the button from the tool tile. Therefore create immediately.
=> #3384 shortcut create

news/3384.added.rst, src/euphorie/client/browser/templates/consultancy.pt, src/euphorie/deployment/locales/euphorie.pot, src/euphorie/deployment/locales/nl/LC_MESSAGES/euphorie.po, src/euphorie/deployment/locales/nl_BE/LC_MESSAGES/euphorie.po
Show info on the consultancy view depending on the role of the user.
External users (consultants) don't need to know about the consultancy feature but they need to know if there is work for them to do or not at the moment.
=> #3384 consultancy

docs/changes.rst, src/euphorie/content/browser/configure.zcml, src/euphorie/content/browser/survey.py, src/euphorie/content/browser/templates/list-links.pt
Ref https://github.com/syslabcom/scrum/issues/2757
=> Add view that lists all links in a tool

news/+16ff4214.breaking.rst, src/euphorie/content/sector.py, src/euphorie/content/widgets/logo.py, src/euphorie/content/widgets/logo_bbb.py, src/euphorie/content/widgets/templates/logo.pt
Do not use anymore the logo widget because the help text is not updated anymore. Update the field help text.
Refs. https://github.com/syslabcom/scrum/issues/3061
=> Change the logo widget

setup.py, src/euphorie/client/browser/settings.py, src/euphorie/client/tests/test_settings.py, versions-6.1.cfg
Remove dependency from the obsolete package z3c.schema
This also makes the email fields consistent across the forms (they all use `plone.schema.Email` now).
=> Support Plone 6

news/3800.bugfix.rst, src/euphorie/client/browser/training.py
Fixes an issue for archived sessions when the survey is republished with a removed risk. Refs https://github.com/syslabcom/scrum/issues/3800
=> Training generation is more resilient

src/euphorie/client/authentication.py
I tried creating a user via `@@new-user` and got an error because our PAS plugin was immediately trying to create a client-side user in SQL:
```
Traceback (most recent call last):
File "/Users/maurits/shared-eggs/cp311/plone.app.users-3.1.3-py3.11.egg/plone/app/users/browser/register.py", line 427, in handle_join_success
registration.addMember(user_id, password, REQUEST=self.request)
File "/Users/maurits/shared-eggs/cp311/Products.CMFCore-3.7-py3.11.egg/Products/CMFCore/RegistrationTool.py", line 161, in addMember
mtool.addMember(id, password, roles, domains, properties)
File "/Users/maurits/shared-eggs/cp311/Products.PlonePAS-8.0.5-py3.11.egg/Products/PlonePAS/tools/membership.py", line 140, in addMember
acl_users._doAddUser(id, password, roles, domains)
File …
```
=> Fix error when creating backend user.
